server:
  port: 8020
  servlet:
    context-path: /benchmarking

spring:
  application:
    name: benchmaring
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
      strict: false
      primary: benchmarking
      datasource:
        benchmarking:
          url: jdbc:mysql://127.0.0.1:3306/benchmarking?serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  mapperLocations: mapper/*.xml

logging:
  config: classpath:logback-spring.xml

auth:
  no-token-path: /login;/logout;/swagger-ui.html;/swagger-resources;/v2/api-docs;/configuration/security;/configuration/ui;/doc.html;/webjars/**;/favicon.ico;/v3/**
